INSERT INTO TRANSACTION (ROWTIME, KEY, TIMESTAMP, WITHDRAWN) VALUES (UNIX_TIMESTAMP(), '1', UNIX_TIMESTAMP(), STRUCT(AMOUNT:=-10, ATM:='abc'));
INSERT INTO TRANSACTION (ROWTIME, KEY, TIMESTAMP, DEPOSIT) VALUES (UNIX_TIMESTAMP(), '1', UNIX_TIMESTAMP(), STRUCT(AMOUNT:=100, ATM:='abc'));

